name: netspeed_si
description: Ping based network tester

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-139.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  easyping: ^1.0.1
  localstorage: ^4.0.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/cloud_turtle_balloon_animation_reverse_scale.gif
    - assets/slow_trans_white.png
    - assets/fast_trans_white.png
    - assets/suff_trans_white.png
 
  fonts:
    - family: MontserratSubrayada
      fonts:
        - asset: fonts/MontserratSubrayada-Regular.ttf

